<p><a href="http://codex.wordpress.org/Excerpt" target="_blank">Text Ads </a></p>
<img src="<?php echo img_src('logo.jpg'); ?>" width="150" class="logo" />
<h3>Links</h3>
<p>Select the Post or Page link(s) you wish to Wag by checking the box nest to the Title. If you do not wish to Wag specifc links, uncheck uncheck the box next to the Title</p>
<p>Click "Save Changes" to update</p>
<div class="data">
<form name="test" action="">
<h4>Posts</h4>		
<div id="content_text">
 				<div class="f_row">
                            <div class="f_left">Wag my previously created links 1 </div>
                            <div class="f_right"><input class="txt_field" name="username" type="checkbox" checked="checked" /></div>
						</div>
 						 <div class="f_row">
                            <div class="f_left">Automatically Wag all new Posts: </div>
                            <div class="f_right"><input class="txt_field" name="username" type="checkbox" checked="checked" /></div>
						</div>
                        <div class="f_row">
                            <div class="f_left">Automatically Wag all new Pages: </div>
                            <div class="f_right"><input class="txt_field" name="username" type="checkbox" checked="checked" /></div>
						</div>
                        <div class="f_row">
                            <div class="f_left">Add LinkWag icon to the end of Post content: </div>
                            <div class="f_right"><input class="txt_field" name="username" type="checkbox" checked="checked" /></div>
						</div>
                        <div class="f_row">
                            <div class="f_left">Add LinkWag icon to the end of Page content: </div>
                            <div class="f_right"><input class="txt_field" name="username" type="checkbox" checked="checked" /></div>
						</div>
</div> 		

<h4>Pages</h4>
<div id="content_text">
 						<div class="f_row">
                            <div class="f_left">Wag my previously created links 1 </div>
                            <div class="f_right"><input class="txt_field" name="username" type="checkbox" checked="checked" /></div>
						</div>
 						 <div class="f_row">
                            <div class="f_left">Automatically Wag all new Posts: </div>
                            <div class="f_right"><input class="txt_field" name="username" type="checkbox" checked="checked" /></div>
						</div>
                        <div class="f_row">
                            <div class="f_left">Automatically Wag all new Pages: </div>
                            <div class="f_right"><input class="txt_field" name="username" type="checkbox" checked="checked" /></div>
						</div>
                        <div class="f_row">
                            <div class="f_left">Add LinkWag icon to the end of Post content: </div>
                            <div class="f_right"><input class="txt_field" name="username" type="checkbox" checked="checked" /></div>
						</div>
                        <div class="f_row">
                            <div class="f_left">Add LinkWag icon to the end of Page content: </div>
                            <div class="f_right"><input class="txt_field" name="username" type="checkbox" checked="checked" /></div>
						</div>
</div> 						
                        <div class="f_row last">
                            <div class="f_left"><input type="submit" class="submit_btn" value=" Save Changes"  /></div>
                            <div class="f_right">&nbsp;</div>
						</div>
                        
                        
                        
</form>

</div>